---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APP_NAME>
  namespace: <NAMESPACE>
  labels:
    app: <APP_NAME>
spec:
  replicas: 2
  selector:
    matchLabels:
      app: <APP_NAME>
  template:
    metadata:
      labels:
        app: <APP_NAME>
    spec:
      containers:
        - image: 39.101.1.156:89/<APP_NAME>/<APP_NAME>:<APP_TAG>
          imagePullPolicy: Always
          name: <APP_NAME>
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: harbor
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: <APP_NAME>
  name: <APP_NAME>
  namespace: <NAMESPACE>
spec:
  selector:
    app: <APP_NAME>
  ports:
  - port: 8080
    targetPort: 80
  type: NodePort
---   
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: pipeline
  namespace: test
spec:
  ingressClassName: pipeline
  rules:
  - host: "pipeline.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: pipeline
            port:
              number: 8080
 

    


